import { WORKSPACE_OUTPUT_TEMPLATE } from "./workspace-output-surface.js";

export const PHOTO_EDITOR_TEMPLATE = `                <div class="photo-tools-view" id="photo-tools-view-edit" data-photo-tools-view="edit" hidden>
                  <header class="photo-tools-view-header"><h3>Edit</h3><button type="button" class="quiet" data-photo-tools-return>Photo tools</button></header>
                  <div class="photo-editor-controls" aria-label="Photo edit">
                    <p class="photo-editor-status" data-photo-editor-status role="status" aria-live="polite"></p>
                    <p class="photo-editor-preview-note" data-photo-editor-render-status role="status"></p>
                    <img class="photo-editor-preview-image" data-photo-editor-preview-image alt="Current edit preview" hidden>
                    <p class="photo-editor-preview-note" data-photo-editor-preview-note hidden></p>
                    <div class="photo-editor-view-actions" role="group" aria-label="Edit view"><button type="button" data-photo-editor-stage="film" aria-pressed="false" disabled>Film</button><button type="button" class="quiet" data-photo-editor-stage="camera" aria-pressed="false">Original reference</button></div>
                    <p class="photo-editor-stage-note" id="photo-editor-stage-note" data-photo-editor-stage-note role="status" hidden></p>
                    <div class="photo-editor-field"><label for="photo-editor-exposure">Exposure</label><output data-photo-editor-exposure-value for="photo-editor-exposure">0.000 EV</output><input id="photo-editor-exposure" data-photo-editor-exposure type="range" min="0" max="1" step="0.001" value="0" aria-label="Exposure" disabled><button type="button" class="quiet" data-photo-editor-reset-exposure disabled>Reset exposure</button></div>
                    <div class="photo-editor-field photo-editor-white-balance">
                      <label for="photo-editor-white-balance-mode">White balance</label>
                      <select id="photo-editor-white-balance-mode" data-photo-editor-white-balance-mode disabled><option value="as-shot">As shot</option><option value="temperature-tint" disabled>Temperature &amp; tint</option></select>
                      <p class="photo-editor-note" data-photo-editor-white-balance-note hidden></p>
                      <div class="photo-editor-field"><label for="photo-editor-temperature">Temperature</label><output data-photo-editor-temperature-value for="photo-editor-temperature">—</output><input id="photo-editor-temperature" data-photo-editor-temperature type="range" min="1000" max="40000" step="1" value="6500" aria-label="Temperature in Kelvin" disabled></div>
                      <div class="photo-editor-field"><label for="photo-editor-tint">Tint</label><output data-photo-editor-tint-value for="photo-editor-tint">—</output><input id="photo-editor-tint" data-photo-editor-tint type="range" min="-150000" max="150000" step="1" value="0" aria-label="Tint" disabled></div>
                      <button type="button" class="quiet" data-photo-editor-reset-white-balance disabled>Reset white balance</button>
                    </div>
                    <p class="photo-editor-note" data-photo-editor-controls-readonly hidden></p>
                    <div class="photo-editor-actions"><button type="button" class="quiet" data-photo-editor-undo disabled>Undo</button><button type="button" class="quiet" data-photo-editor-redo disabled>Redo</button><button type="button" class="quiet" data-photo-editor-reset disabled>Reset</button><button type="button" class="quiet" data-photo-editor-compare aria-pressed="false" title="Press to compare the current settings with the unadjusted rendering" disabled>Baseline comparison</button><button type="button" data-photo-editor-preview disabled>Refresh preview</button><button type="button" class="quiet" data-photo-editor-rebind hidden disabled>Keep edit for the current file</button><button type="button" class="quiet" data-photo-editor-refresh>Reload edit</button></div>
                    <p class="photo-editor-draft" data-photo-editor-draft hidden role="status"></p>
                    <div class="photo-editor-conflict" data-photo-editor-conflict hidden><p data-photo-editor-conflict-message role="alert"></p><div class="photo-editor-actions"><button type="button" data-photo-editor-use-saved>Use saved edit</button><button type="button" class="quiet" data-photo-editor-reapply>Reapply my changes</button><button type="button" class="quiet" data-photo-editor-discard-draft>Discard draft</button></div></div>
                    <div class="photo-editor-composable" data-photo-editor-composable aria-label="Processing Steps">
                      <p class="photo-editor-export-heading">Processing Steps</p>
                      <p class="photo-editor-composable-state" data-photo-editor-composable-state role="status"></p>
                      <div class="photo-editor-actions" data-photo-editor-composable-start hidden><button type="button" data-photo-editor-compose>Compose Processing Steps</button></div>
                      <div class="photo-editor-composable-body" data-photo-editor-composable-body hidden>
                        <ul class="photo-editor-composable-steps" data-photo-editor-composable-steps></ul>
                        <div class="photo-editor-actions"><label class="quiet" for="photo-editor-composable-module">Add step</label><select id="photo-editor-composable-module" data-photo-editor-composable-module></select><button type="button" data-photo-editor-composable-add>Add step</button></div>
                        <div class="photo-editor-composable-editor" data-photo-editor-composable-editor hidden>
                          <p class="photo-editor-composable-editing"><span data-photo-editor-composable-editing-step></span> <span data-photo-editor-composable-editing-module></span></p>
                          <div class="photo-editor-field"><label for="photo-editor-composable-schema">Parameter version</label><select id="photo-editor-composable-schema" data-photo-editor-composable-schema></select></div>
                          <fieldset class="photo-editor-composable-input"><legend>Step input</legend><label><input type="radio" name="photo-editor-composable-input" value="original" data-photo-editor-composable-input-original> The guarded Original of this Photo</label><label><input type="radio" name="photo-editor-composable-input" value="artifact" data-photo-editor-composable-input-artifact> One retained Processing Artifact</label><div class="photo-editor-actions"><select data-photo-editor-composable-artifact aria-label="Retained Processing Artifacts"></select></div></fieldset>
                          <div class="photo-editor-field"><label for="photo-editor-composable-parameters">Module parameters (JSON)</label><textarea id="photo-editor-composable-parameters" data-photo-editor-composable-parameters rows="8" spellcheck="false"></textarea><p class="photo-editor-note" data-photo-editor-composable-parameters-note hidden></p></div>
                        </div>
                        <div class="photo-editor-actions"><button type="button" data-photo-editor-composable-save>Save Processing Recipe</button><button type="button" class="quiet" data-photo-editor-composable-discard hidden>Discard changes</button></div>
                        <div class="photo-editor-composable-artifacts" data-photo-editor-composable-artifacts hidden>
                          <p class="photo-editor-export-heading">Processing Artifacts</p>
                          <ul class="photo-editor-composable-artifact-list" data-photo-editor-composable-artifact-list></ul>
                          <div class="photo-editor-actions"><label class="quiet" for="photo-editor-composable-artifact-id">Artifact identity</label><input id="photo-editor-composable-artifact-id" data-photo-editor-composable-artifact-id type="text" autocomplete="off"><button type="button" class="quiet" data-photo-editor-composable-artifact-fetch>Read artifact</button></div>
                        </div>
                      </div>
                    </div>
                    <div class="photo-editor-export" aria-label="Export"><p class="photo-editor-export-heading">Export <span data-photo-editor-export-target>Development TIFF</span></p><p class="photo-editor-export-state" data-photo-editor-export-state role="status"></p><div class="photo-editor-actions"><button type="button" data-photo-editor-export-submit>Export Development TIFF</button><button type="button" class="quiet" data-photo-editor-export-check hidden>Check status</button><button type="button" class="quiet" data-photo-editor-export-cancel hidden>Cancel</button><button type="button" class="quiet" data-photo-editor-export-retry hidden>Retry</button><button type="button" class="quiet" data-photo-editor-export-download hidden>Download</button></div></div>
                    ${WORKSPACE_OUTPUT_TEMPLATE}
                    <details class="photo-editor-details"><summary>Details</summary><p data-photo-editor-provenance></p><p data-photo-editor-detail hidden></p><p data-photo-editor-capability hidden></p><p class="photo-editor-fact"><span>White balance</span><span data-photo-editor-white-balance>As shot</span></p><p class="photo-editor-fact"><span>Edit source</span><span data-photo-editor-support>Checking…</span></p><p class="photo-editor-fact"><span>Development Proxy</span><span data-photo-editor-proxy-state>Checking…</span></p><div class="photo-editor-actions"><button type="button" class="quiet" data-photo-editor-proxy-create disabled>Create Development Proxy</button><button type="button" class="quiet" data-photo-editor-proxy-remove hidden disabled>Remove Development Proxy</button></div><p class="photo-editor-fact"><span>Processing</span><span data-photo-editor-processing>Checking…</span></p><p class="photo-editor-fact"><span>Edit Preview</span><span data-photo-editor-preview-state>Checking…</span></p></details>
                  </div>
                </div>`;
