[package]
name = "slipstream-core"
build = "build.rs"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
lcms2.workspace = true
libc.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true

[build-dependencies]
cc.workspace = true
pkg-config.workspace = true

[dev-dependencies]
serde.workspace = true
