//! Immutable derivative cache identity, publication, failure records, and scheduling.
//!
//! The cache is deliberately separate from [`crate::confinement::LibraryRoot`].  It owns
//! generated bytes, while Originals remain read-only capabilities held by the caller.

#[path = "cache_metadata.rs"]
mod cache_metadata;

#[path = "cache_jpeg.rs"]
mod cache_jpeg;

use cache_jpeg::{jpeg_facts, validate_cached_jpeg, validate_jpeg_bytes, validate_processed};
#[cfg(test)]
use cache_metadata::DerivativeProfileWire;
use cache_metadata::{
    FailureRecord, Manifest, ManifestFacts, PersistentFailureKind, failure_record,
    manifest_is_for_photo_target, manifest_is_stale_for_identity, manifest_key_is_valid,
    manifest_matches_identity, manifest_record, read_failure, read_manifest, serialize_failure,
    serialize_manifest,
};

use crate::{
    OriginalRecord, PhotoRecord, PreviewSource,
    derivative::{
        Derivative, DerivativeError, DerivativeProfile, DerivativeTarget,
        process_jpeg_with_orientation,
    },
    native_work::{NativeWorkBudget, NativeWorkPermit},
    source_revision,
};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    collections::{HashMap, HashSet, VecDeque},
    fs::{self, OpenOptions},
    io::{self, Read, Write},
    path::{Component, Path, PathBuf},
    sync::{
        Arc, Condvar, Mutex, OnceLock, Weak,
        atomic::{AtomicU64, Ordering},
    },
    thread::{self, JoinHandle},
};

#[cfg(unix)]
use std::os::unix::fs::OpenOptionsExt;

pub const DERIVATIVE_ALGORITHM_VERSION: &str = "rust-vips-v2";
pub const DEFAULT_WORKERS: usize = 2;
pub const DEFAULT_QUEUE_CAPACITY: usize = 64;
pub const DEFAULT_WAITER_CAPACITY: usize = 64;
pub const MAXIMUM_OUTPUT_BYTES: u64 = 64 * 1024 * 1024;
const CACHE_RECORD_SCHEMA_VERSION: u32 = 2;
const MAXIMUM_METADATA_BYTES: u64 = 16 * 1024;
const CACHE_NAMESPACE: &str = "rust-vips-v2";

type JobResult = Result<DerivativeResult, CacheError>;
pub type DerivativeProcess = dyn Fn(&[u8], Option<u8>, DerivativeTarget) -> Result<Derivative, DerivativeError>
    + Send
    + Sync;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum DerivativeSource {
    MatchingJpeg,
    EmbeddedRawJpeg,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DerivativeIdentity {
    pub photo_identity: String,
    pub source: DerivativeSource,
    pub source_relative_path: String,
    pub source_size: u64,
    pub source_mtime_ms: f64,
    pub embedded_candidate_identity: Option<String>,
    pub target: DerivativeTarget,
}

impl DerivativeIdentity {
    pub fn validate(&self) -> Result<(), CacheError> {
        if self.photo_identity.is_empty() || self.photo_identity.contains('\0') {
            return Err(CacheError::InvalidIdentity);
        }
        if self.source_relative_path.as_bytes().contains(&0)
            || !is_safe_relative_utf8_path(&self.source_relative_path)
        {
            return Err(CacheError::InvalidIdentity);
        }
        if !self.source_mtime_ms.is_finite() || self.source_mtime_ms < 0.0 {
            return Err(CacheError::InvalidIdentity);
        }
        if self.source == DerivativeSource::MatchingJpeg
            && self.embedded_candidate_identity.is_some()
        {
            return Err(CacheError::InvalidIdentity);
        }
        if let Some(candidate) = &self.embedded_candidate_identity
            && (candidate.is_empty() || candidate.contains('\0'))
        {
            return Err(CacheError::InvalidIdentity);
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CacheError {
    Saturated,
    Closed,
    InvalidCacheDirectory,
    InvalidIdentity,
    UnsupportedEncoding,
    Io,
    InvalidCachedDerivative,
    Invalidated,
}

impl std::fmt::Display for CacheError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(match self {
            Self::Saturated => "Derivative scheduler is saturated",
            Self::Closed => "Derivative scheduler is closed",
            Self::InvalidCacheDirectory => "Derivative cache directory is invalid",
            Self::InvalidIdentity => "Derivative identity is invalid",
            Self::UnsupportedEncoding => "Derivative cache path encoding is unsupported",
            Self::Io => "Derivative cache I/O failed",
            Self::InvalidCachedDerivative => "Cached derivative failed validation",
            Self::Invalidated => "Derivative generation was invalidated",
        })
    }
}

impl std::error::Error for CacheError {}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum DerivativePriority {
    Current,
    Adjacent,
    VisibleGrid,
    Background,
}

impl DerivativePriority {
    pub(crate) const fn rank(self) -> u8 {
        match self {
            Self::Current => 0,
            Self::Adjacent => 1,
            Self::VisibleGrid => 2,
            Self::Background => 3,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct CachedDerivative {
    pub cache_path: PathBuf,
    pub cache_key: String,
    pub source: DerivativeSource,
    pub source_relative_path: String,
    pub source_size: u64,
    pub source_mtime_ms: f64,
    pub embedded_candidate_identity: Option<String>,
    pub width: u32,
    pub height: u32,
    pub profile: DerivativeProfile,
    pub generated: bool,
    pub stale: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DerivativeFailureKind {
    Unsupported,
    Malformed,
    ResourceLimit,
    OutputLimit,
    Io,
    Internal,
}

impl From<PersistentFailureKind> for DerivativeFailureKind {
    fn from(kind: PersistentFailureKind) -> Self {
        match kind {
            PersistentFailureKind::Unsupported => Self::Unsupported,
            PersistentFailureKind::Malformed => Self::Malformed,
            PersistentFailureKind::ResourceLimit => Self::ResourceLimit,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DerivativeFailure {
    pub kind: DerivativeFailureKind,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DerivativeResult {
    Ready(CachedDerivative),
    Failed(DerivativeFailure),
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CacheDirectory {
    root: Arc<CacheDirectoryInner>,
}

#[derive(Debug, Eq, PartialEq)]
struct CacheDirectoryInner {
    canonical_root: PathBuf,
    namespace_root: PathBuf,
    canonical_original_root: PathBuf,
}

impl CacheDirectory {
    /// Opens an owned cache directory and rejects a cache located below Originals.
    ///
    /// The canonical path is retained after this check. All generated names are fixed
    /// hexadecimal names or private temporary names, so identities never become paths.
    pub fn open(
        cache_directory: impl AsRef<Path>,
        original_root: impl AsRef<Path>,
    ) -> Result<Self, CacheError> {
        let cache_directory = cache_directory.as_ref();
        let original_root = original_root.as_ref();
        if !cache_directory.is_absolute() || !original_root.is_absolute() {
            return Err(CacheError::InvalidCacheDirectory);
        }
        if cache_directory.to_str().is_none() || original_root.to_str().is_none() {
            return Err(CacheError::UnsupportedEncoding);
        }
        let canonical_original_root =
            fs::canonicalize(original_root).map_err(|_| CacheError::InvalidCacheDirectory)?;
        if !canonical_original_root.is_dir() {
            return Err(CacheError::InvalidCacheDirectory);
        }
        reject_cache_under_original(cache_directory, &canonical_original_root)?;
        fs::create_dir_all(cache_directory).map_err(|_| CacheError::Io)?;
        let canonical_root = fs::canonicalize(cache_directory).map_err(|_| CacheError::Io)?;
        if !canonical_root.is_dir()
            || canonical_root == canonical_original_root
            || canonical_root.starts_with(&canonical_original_root)
        {
            return Err(CacheError::InvalidCacheDirectory);
        }
        if canonical_root.to_str().is_none() {
            return Err(CacheError::UnsupportedEncoding);
        }
        let namespace_path = canonical_root.join(CACHE_NAMESPACE);
        fs::create_dir_all(&namespace_path).map_err(|_| CacheError::Io)?;
        let namespace_root = fs::canonicalize(&namespace_path).map_err(|_| CacheError::Io)?;
        if !namespace_root.is_dir()
            || !namespace_root.starts_with(&canonical_root)
            || namespace_root.to_str().is_none()
        {
            return Err(CacheError::InvalidCacheDirectory);
        }
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut permissions = fs::metadata(&canonical_root)
                .map_err(|_| CacheError::Io)?
                .permissions();
            permissions.set_mode(0o700);
            fs::set_permissions(&canonical_root, permissions).map_err(|_| CacheError::Io)?;
        }
        Ok(Self {
            root: Arc::new(CacheDirectoryInner {
                canonical_root,
                namespace_root,
                canonical_original_root,
            }),
        })
    }

    pub fn root(&self) -> &Path {
        &self.root.canonical_root
    }

    pub fn original_root(&self) -> &Path {
        &self.root.canonical_original_root
    }

    /// Looks up one current derivative from persisted cache metadata and the
    /// Library's published source facts. This path never opens an Original.
    /// Missing or invalid cache state is a miss so callers can use the normal
    /// bounded source-inspection path.
    pub fn lookup_current(
        &self,
        photo: &PhotoRecord,
        originals: &[OriginalRecord],
        target: DerivativeTarget,
    ) -> Result<Option<CachedDerivative>, CacheError> {
        let Some(manifest) = self.current_manifest(photo, originals, target)? else {
            return Ok(None);
        };
        let Some(facts) = inspect_cached(&self.derivative_path(&manifest.key), target, &manifest)
        else {
            return Ok(None);
        };
        Ok(Some(cached_from_manifest(
            self, manifest, facts, false, false,
        )))
    }

    /// Returns the current manifest key after bounded metadata checks. This is
    /// only for Browse Window URL hydration; Preview requests and derivative
    /// delivery perform complete JPEG validation before serving bytes.
    pub fn lookup_current_key(
        &self,
        photo: &PhotoRecord,
        originals: &[OriginalRecord],
        target: DerivativeTarget,
    ) -> Result<Option<String>, CacheError> {
        Ok(self
            .current_manifest(photo, originals, target)?
            .map(|manifest| manifest.key))
    }

    fn current_manifest(
        &self,
        photo: &PhotoRecord,
        originals: &[OriginalRecord],
        target: DerivativeTarget,
    ) -> Result<Option<Manifest>, CacheError> {
        let path = self.manifest_path_for_photo_target(&photo.id, target)?;
        let Ok(manifest) = read_manifest(&path) else {
            return Ok(None);
        };
        let Some((source, original)) = selected_original(photo, originals) else {
            return Ok(None);
        };

        let manifest_source = match source {
            PreviewSource::JpegOriginal => DerivativeSource::MatchingJpeg,
            PreviewSource::RawEmbeddedJpeg => DerivativeSource::EmbeddedRawJpeg,
        };
        if !manifest_key_is_valid(&manifest)
            || manifest.photo_identity != photo.id
            || manifest.target_long_edge != target.long_edge()
            || manifest.source != manifest_source
            || manifest.source_relative_path != original.relative_path.as_str()
            || manifest.source_size != original.facts.size
            || manifest.source_mtime_ms != original.facts.mtime_ms
            || (source == PreviewSource::JpegOriginal
                && manifest.embedded_candidate_identity.is_some())
            || photo
                .preview_source_revision
                .as_deref()
                .is_some_and(|stored| {
                    stored
                        != source_revision(
                            original.relative_path.as_str(),
                            original.facts.size,
                            original.facts.mtime_ms,
                        )
                        .ok()
                        .as_deref()
                        .unwrap_or("")
                })
        {
            return Ok(None);
        }
        let metadata = fs::symlink_metadata(self.derivative_path(&manifest.key)).ok();
        if !metadata.is_some_and(|metadata| {
            metadata.is_file() && metadata.len() > 0 && metadata.len() <= MAXIMUM_OUTPUT_BYTES
        }) {
            return Ok(None);
        }
        Ok(Some(manifest))
    }

    fn manifest_path_for_photo_target(
        &self,
        photo_id: &str,
        target: DerivativeTarget,
    ) -> Result<PathBuf, CacheError> {
        let identity = manifest_identity_for_photo_target(photo_id, target)?;
        Ok(self
            .root
            .namespace_root
            .join("metadata")
            .join("manifests")
            .join(format!("{identity}.json")))
    }

    /// Reads one already-published derivative by its cache identity.
    ///
    /// Callers provide only the validated hexadecimal identity; cache path
    /// construction and no-follow file admission remain inside the cache
    /// boundary. This keeps filesystem paths out of the HTTP and Preview APIs.
    pub fn read_derivative(
        &self,
        key: &str,
        target: DerivativeTarget,
    ) -> Result<Vec<u8>, CacheError> {
        if !is_hex_key(key) {
            return Err(CacheError::InvalidIdentity);
        }
        let path = self.derivative_path(key);
        let file = OpenOptions::new()
            .read(true)
            .custom_flags(no_follow_flag())
            .open(path)
            .map_err(|_| CacheError::Io)?;
        let metadata = file.metadata().map_err(|_| CacheError::Io)?;
        if !metadata.is_file() || metadata.len() == 0 || metadata.len() > MAXIMUM_OUTPUT_BYTES {
            return Err(CacheError::InvalidCachedDerivative);
        }
        let mut bytes = Vec::with_capacity(metadata.len() as usize);
        file.take(MAXIMUM_OUTPUT_BYTES + 1)
            .read_to_end(&mut bytes)
            .map_err(|_| CacheError::Io)?;
        if bytes.len() as u64 > MAXIMUM_OUTPUT_BYTES {
            return Err(CacheError::InvalidCachedDerivative);
        }
        let Some(facts) = jpeg_facts(&bytes) else {
            return Err(CacheError::InvalidCachedDerivative);
        };
        if facts.width.max(facts.height) > target.long_edge()
            || validate_jpeg_bytes(&bytes, facts, false).is_none()
        {
            return Err(CacheError::InvalidCachedDerivative);
        }
        Ok(bytes)
    }

    fn derivative_path(&self, key: &str) -> PathBuf {
        self.root.namespace_root.join(format!("{key}.jpg"))
    }

    fn manifest_path(&self, identity: &DerivativeIdentity) -> Result<PathBuf, CacheError> {
        self.manifest_path_for_photo_target(&identity.photo_identity, identity.target)
    }

    fn failure_path(&self, key: &str) -> PathBuf {
        self.root
            .namespace_root
            .join("metadata")
            .join("failures")
            .join(format!("{key}.json"))
    }

    fn ensure_metadata(&self) -> Result<(), CacheError> {
        fs::create_dir_all(self.root.namespace_root.join("metadata/manifests"))
            .map_err(|_| CacheError::Io)?;
        fs::create_dir_all(self.root.namespace_root.join("metadata/failures"))
            .map_err(|_| CacheError::Io)?;
        Ok(())
    }
}

#[derive(Clone)]
struct JobCell {
    value: Arc<(Mutex<Option<JobResult>>, Condvar)>,
}

impl JobCell {
    fn new() -> Self {
        Self {
            value: Arc::new((Mutex::new(None), Condvar::new())),
        }
    }

    fn complete(&self, result: Result<DerivativeResult, CacheError>) {
        let (lock, signal) = &*self.value;
        let mut value = lock.lock().expect("job cell poisoned");
        if value.is_none() {
            *value = Some(result);
            signal.notify_all();
        }
    }

    fn wait(&self) -> Result<DerivativeResult, CacheError> {
        let (lock, signal) = &*self.value;
        let mut result = lock.lock().expect("job cell poisoned");
        while result.is_none() {
            result = signal.wait(result).expect("job cell poisoned");
        }
        result
            .as_ref()
            .expect("job cell result disappeared")
            .clone()
    }
}

fn invalidate_detached(detached: Vec<JobCell>) {
    for cell in detached {
        cell.complete(Err(CacheError::Invalidated));
    }
}

/// Releases one admitted waiter slot after its blocking work finishes.
fn release_waiter_slot(inner: &SchedulerInner) {
    let mut state = inner.state.lock().expect("scheduler state poisoned");
    state.waiter_count = state.waiter_count.saturating_sub(1);
}

struct JobMeta {
    priority: Mutex<DerivativePriority>,
    order: u64,
}

struct QueuedJob {
    identity: DerivativeIdentity,
    jpeg: Vec<u8>,
    container_orientation: Option<u8>,
    key: String,
    manifest_key: String,
    generation: u64,
    meta: Arc<JobMeta>,
    cell: JobCell,
}

struct InFlight {
    cell: JobCell,
    meta: Arc<JobMeta>,
    manifest_key: String,
    generation: u64,
}

struct SchedulerState {
    closed: bool,
    terminate_workers: bool,
    active: usize,
    next_order: u64,
    next_generation: u64,
    waiter_count: usize,
    queue: VecDeque<QueuedJob>,
    in_flight: HashMap<String, InFlight>,
    authoritative: HashMap<String, u64>,
    invalidating: HashSet<String>,
    failed: HashMap<String, DerivativeFailure>,
}

impl SchedulerState {
    fn generation_is_authoritative(&self, manifest_key: &str, generation: u64) -> bool {
        self.authoritative.get(manifest_key).copied() == Some(generation)
    }

    /// Detaches queued jobs selected by `detach` and returns their cells so the
    /// caller can invalidate waiters after releasing the state lock.
    fn detach_queued(&mut self, mut detach: impl FnMut(&QueuedJob) -> bool) -> Vec<JobCell> {
        let mut detached = Vec::new();
        self.queue.retain(|job| {
            if detach(job) {
                detached.push(job.cell.clone());
                false
            } else {
                true
            }
        });
        detached
    }
}

struct SchedulerInner {
    cache: CacheDirectory,
    native_work: NativeWorkBudget,
    state: Mutex<SchedulerState>,
    signal: Condvar,
    workers: Mutex<Vec<JoinHandle<()>>>,
    worker_count: usize,
    queue_capacity: usize,
    waiter_capacity: usize,
    process: Arc<DerivativeProcess>,
}

static SCHEDULERS: OnceLock<Mutex<HashMap<PathBuf, Weak<SchedulerInner>>>> = OnceLock::new();
static NEXT_TEMPORARY: AtomicU64 = AtomicU64::new(0);

#[derive(Clone)]
pub struct DerivativeScheduler {
    inner: Arc<SchedulerInner>,
}

#[derive(Clone)]
pub struct DerivativeSchedulerOptions {
    pub workers: usize,
    pub queue_capacity: usize,
    pub waiter_capacity: usize,
    pub process: Option<Arc<DerivativeProcess>>,
}

impl Default for DerivativeSchedulerOptions {
    fn default() -> Self {
        Self {
            workers: DEFAULT_WORKERS,
            queue_capacity: DEFAULT_QUEUE_CAPACITY,
            waiter_capacity: DEFAULT_WAITER_CAPACITY,
            process: None,
        }
    }
}

impl DerivativeScheduler {
    pub fn new(cache: CacheDirectory) -> Result<Self, CacheError> {
        Self::with_options(cache, DerivativeSchedulerOptions::default())
    }

    pub fn with_options(
        cache: CacheDirectory,
        options: DerivativeSchedulerOptions,
    ) -> Result<Self, CacheError> {
        Self::with_native_work_budget(cache, options, NativeWorkBudget::new())
    }

    pub(crate) fn with_native_work_budget(
        cache: CacheDirectory,
        options: DerivativeSchedulerOptions,
        native_work: NativeWorkBudget,
    ) -> Result<Self, CacheError> {
        if options.workers == 0 || options.queue_capacity == 0 || options.waiter_capacity == 0 {
            return Err(CacheError::InvalidCacheDirectory);
        }
        cache.ensure_metadata()?;
        let registry = SCHEDULERS.get_or_init(|| Mutex::new(HashMap::new()));
        let mut entries = registry.lock().expect("scheduler registry poisoned");
        if let Some(existing) = entries.get(cache.root()).and_then(Weak::upgrade) {
            if existing.worker_count != options.workers
                || existing.queue_capacity != options.queue_capacity
                || existing.waiter_capacity != options.waiter_capacity
            {
                return Err(CacheError::InvalidCacheDirectory);
            }
            return Ok(Self { inner: existing });
        }
        let cache_root = cache.root().to_owned();
        let inner = Arc::new(SchedulerInner {
            cache,
            native_work,
            state: Mutex::new(SchedulerState {
                closed: false,
                terminate_workers: false,
                active: 0,
                next_order: 0,
                next_generation: 0,
                waiter_count: 0,
                queue: VecDeque::new(),
                in_flight: HashMap::new(),
                authoritative: HashMap::new(),
                invalidating: HashSet::new(),
                failed: HashMap::new(),
            }),
            signal: Condvar::new(),
            workers: Mutex::new(Vec::new()),
            worker_count: options.workers,
            queue_capacity: options.queue_capacity,
            waiter_capacity: options.waiter_capacity,
            process: options
                .process
                .unwrap_or_else(|| Arc::new(process_jpeg_with_orientation)),
        });
        let mut workers = inner.workers.lock().expect("worker list poisoned");
        for index in 0..inner.worker_count {
            let worker = Arc::clone(&inner);
            workers.push(
                thread::Builder::new()
                    .name(format!("slipstream-derivative-{index}"))
                    .spawn(move || worker_loop(worker))
                    .map_err(|_| CacheError::Io)?,
            );
        }
        drop(workers);
        entries.insert(cache_root, Arc::downgrade(&inner));
        Ok(Self { inner })
    }

    pub fn cache(&self) -> &CacheDirectory {
        &self.inner.cache
    }

    pub(crate) fn acquire_native_work(&self) -> NativeWorkPermit {
        self.inner.native_work.acquire()
    }

    pub fn generate(
        &self,
        identity: DerivativeIdentity,
        jpeg: Vec<u8>,
        priority: DerivativePriority,
    ) -> Result<DerivativeResult, CacheError> {
        self.generate_with_orientation(identity, jpeg, None, priority)
    }

    pub(crate) fn generate_with_orientation(
        &self,
        identity: DerivativeIdentity,
        jpeg: Vec<u8>,
        container_orientation: Option<u8>,
        priority: DerivativePriority,
    ) -> Result<DerivativeResult, CacheError> {
        identity.validate()?;
        if container_orientation.is_some_and(|value| !(1..=8).contains(&value)) {
            return Err(CacheError::InvalidIdentity);
        }
        let key = derivative_cache_key(&identity)?;
        let manifest_key = manifest_identity(&identity)?;
        let mut detached = Vec::new();
        let cell;
        {
            let mut state = self.inner.state.lock().expect("scheduler state poisoned");
            if state.closed {
                return Err(CacheError::Closed);
            }
            while state.invalidating.contains(&key) {
                state = self
                    .inner
                    .signal
                    .wait(state)
                    .expect("scheduler state poisoned");
                if state.closed {
                    return Err(CacheError::Closed);
                }
            }
            if let Some(failure) = state.failed.get(&key).cloned() {
                state.waiter_count += 1;
                drop(state);
                let result = stale_or_failure(
                    &self.inner,
                    &identity,
                    failure_record(&identity, &key, failure.kind),
                );
                release_waiter_slot(&self.inner);
                return result;
            }
            if state.waiter_count >= self.inner.waiter_capacity {
                return Err(CacheError::Saturated);
            }
            if let Some(existing) = state.in_flight.get(&key) {
                let existing_meta = Arc::clone(&existing.meta);
                let existing_cell = existing.cell.clone();
                let mut existing_priority = existing_meta
                    .priority
                    .lock()
                    .expect("job metadata poisoned");
                if priority < *existing_priority {
                    *existing_priority = priority;
                }
                cell = existing_cell;
            } else {
                if state.queue.len() >= self.inner.queue_capacity {
                    return Err(CacheError::Saturated);
                }
                state.next_order = state
                    .next_order
                    .checked_add(1)
                    .ok_or(CacheError::Saturated)?;
                state.next_generation = state
                    .next_generation
                    .checked_add(1)
                    .ok_or(CacheError::Saturated)?;
                let meta = Arc::new(JobMeta {
                    priority: Mutex::new(priority),
                    order: state.next_order,
                });
                cell = JobCell::new();
                let generation = state.next_generation;
                let manifest_in_flight = state
                    .in_flight
                    .values()
                    .any(|existing| existing.manifest_key == manifest_key);
                state.authoritative.insert(manifest_key.clone(), generation);
                if manifest_in_flight {
                    let mut detached_keys = Vec::new();
                    detached.extend(state.detach_queued(|job| {
                        let superseded = job.manifest_key == manifest_key && job.key != key;
                        if superseded {
                            detached_keys.push(job.key.clone());
                        }
                        superseded
                    }));
                    for detached_key in detached_keys {
                        state.in_flight.remove(&detached_key);
                    }
                }
                state.in_flight.insert(
                    key.clone(),
                    InFlight {
                        cell: cell.clone(),
                        meta: Arc::clone(&meta),
                        manifest_key: manifest_key.clone(),
                        generation,
                    },
                );
                state.queue.push_back(QueuedJob {
                    identity,
                    jpeg,
                    container_orientation,
                    key,
                    manifest_key,
                    generation,
                    meta,
                    cell: cell.clone(),
                });
                self.inner.signal.notify_one();
            }
            state.waiter_count += 1;
        }
        invalidate_detached(detached);
        let result = cell.wait();
        release_waiter_slot(&self.inner);
        result
    }

    pub fn retry(
        &self,
        identity: DerivativeIdentity,
        jpeg: Vec<u8>,
        priority: DerivativePriority,
    ) -> Result<DerivativeResult, CacheError> {
        self.retry_with_orientation(identity, jpeg, None, priority)
    }

    pub(crate) fn retry_with_orientation(
        &self,
        identity: DerivativeIdentity,
        jpeg: Vec<u8>,
        container_orientation: Option<u8>,
        priority: DerivativePriority,
    ) -> Result<DerivativeResult, CacheError> {
        self.invalidate(&identity)?;
        self.generate_with_orientation(identity, jpeg, container_orientation, priority)
    }

    /// Removes the current identity's terminal failure and derivative bytes.
    pub fn invalidate(&self, identity: &DerivativeIdentity) -> Result<(), CacheError> {
        identity.validate()?;
        let key = derivative_cache_key(identity)?;
        let manifest_key = manifest_identity(identity)?;
        let mut state = self.inner.state.lock().expect("scheduler state poisoned");
        state.next_generation = state
            .next_generation
            .checked_add(1)
            .ok_or(CacheError::Saturated)?;
        let generation = state.next_generation;
        state.authoritative.insert(manifest_key, generation);
        state.invalidating.insert(key.clone());
        state.failed.remove(&key);
        // Detach queued work immediately. Active work is also detached from
        // `in_flight`, allowing a same-key retry to enqueue a fresh generation;
        // the worker completion path only removes its own generation below.
        let mut detached = state.detach_queued(|job| job.key == key);
        if let Some(existing) = state.in_flight.get(&key)
            && existing.generation != generation
        {
            detached.push(existing.cell.clone());
            state.in_flight.remove(&key);
        }
        drop(state);
        invalidate_detached(detached);
        let result = (|| {
            remove_if_present(&self.inner.cache.derivative_path(&key))?;
            remove_if_present(&self.inner.cache.failure_path(&key))?;
            let manifest_path = self.inner.cache.manifest_path(identity)?;
            if let Ok(manifest) = read_manifest(&manifest_path)
                && manifest_matches_identity(&manifest, identity)
                && manifest.key == key
            {
                remove_if_present(&manifest_path)?;
            }
            Ok(())
        })();
        let mut state = self.inner.state.lock().expect("scheduler state poisoned");
        state.invalidating.remove(&key);
        self.inner.signal.notify_all();
        result
    }

    /// Stops admission, drains accepted jobs, and waits for every worker to exit.
    pub fn shutdown(&self) -> Result<(), CacheError> {
        let workers = {
            let mut state = self.inner.state.lock().expect("scheduler state poisoned");
            if !state.closed {
                state.closed = true;
                self.inner.signal.notify_all();
            }
            while !(state.queue.is_empty() && state.active == 0 && state.in_flight.is_empty()) {
                state = self
                    .inner
                    .signal
                    .wait(state)
                    .expect("scheduler state poisoned");
            }
            state.terminate_workers = true;
            self.inner.signal.notify_all();
            self.inner
                .workers
                .lock()
                .expect("worker list poisoned")
                .drain(..)
                .collect::<Vec<_>>()
        };
        for worker in workers {
            worker.join().map_err(|_| CacheError::Io)?;
        }
        let registry = SCHEDULERS.get_or_init(|| Mutex::new(HashMap::new()));
        registry
            .lock()
            .expect("scheduler registry poisoned")
            .retain(|_, weak| {
                weak.upgrade()
                    .is_some_and(|inner| !Arc::ptr_eq(&inner, &self.inner))
            });
        Ok(())
    }
}

fn worker_loop(inner: Arc<SchedulerInner>) {
    loop {
        let job = {
            let mut state = inner.state.lock().expect("scheduler state poisoned");
            loop {
                if state.terminate_workers {
                    return;
                }
                if !state.queue.is_empty() {
                    let selected = state
                        .queue
                        .iter()
                        .enumerate()
                        .min_by_key(|(_, job)| {
                            (
                                job.meta
                                    .priority
                                    .lock()
                                    .expect("job metadata poisoned")
                                    .rank(),
                                job.meta.order,
                            )
                        })
                        .map(|(index, _)| index)
                        .expect("nonempty queue");
                    state.active += 1;
                    break state.queue.remove(selected).expect("selected queue job");
                }
                if state.closed && state.active == 0 {
                    state.terminate_workers = true;
                    inner.signal.notify_all();
                    return;
                }
                state = inner.signal.wait(state).expect("scheduler state poisoned");
            }
        };
        let result = generate_one(&inner, &job);
        let mut state = inner.state.lock().expect("scheduler state poisoned");
        state.active = state.active.saturating_sub(1);
        if state
            .in_flight
            .get(&job.key)
            .is_some_and(|in_flight| in_flight.generation == job.generation)
        {
            state.in_flight.remove(&job.key);
        }
        // All result paths, including cache hits and failures, must honor takeover
        // before a waiter can observe their result.
        let result = if state.generation_is_authoritative(&job.manifest_key, job.generation) {
            result
        } else {
            Err(CacheError::Invalidated)
        };
        job.cell.complete(result);
        if state.closed && state.queue.is_empty() && state.active == 0 && state.in_flight.is_empty()
        {
            inner.signal.notify_all();
        } else {
            inner.signal.notify_one();
        }
    }
}

fn job_is_authoritative(inner: &SchedulerInner, job: &QueuedJob) -> bool {
    let state = inner.state.lock().expect("scheduler state poisoned");
    state.generation_is_authoritative(&job.manifest_key, job.generation)
}

fn authoritative_result(
    inner: &SchedulerInner,
    job: &QueuedJob,
    result: Result<DerivativeResult, CacheError>,
) -> Result<DerivativeResult, CacheError> {
    if job_is_authoritative(inner, job) {
        result
    } else {
        Err(CacheError::Invalidated)
    }
}

fn generate_one(inner: &SchedulerInner, job: &QueuedJob) -> Result<DerivativeResult, CacheError> {
    let final_path = inner.cache.derivative_path(&job.key);
    if let Some(failure) =
        read_failure(&inner.cache.failure_path(&job.key), &job.identity, &job.key)
    {
        let mut state = inner.state.lock().expect("scheduler state poisoned");
        if !state.generation_is_authoritative(&job.manifest_key, job.generation) {
            return Err(CacheError::Invalidated);
        }
        state.failed.insert(
            job.key.clone(),
            DerivativeFailure {
                kind: failure.kind.into(),
            },
        );
        drop(state);
        return authoritative_result(inner, job, stale_or_failure(inner, &job.identity, failure));
    }
    if let Ok(manifest) = read_manifest(&inner.cache.manifest_path(&job.identity)?)
        && manifest_matches_identity(&manifest, &job.identity)
        && manifest.key == job.key
        && let Some(facts) = inspect_cached(&final_path, job.identity.target, &manifest)
    {
        return authoritative_result(
            inner,
            job,
            Ok(DerivativeResult::Ready(cached_from_manifest(
                &inner.cache,
                manifest,
                facts,
                false,
                false,
            ))),
        );
    }
    let prior = read_manifest(&inner.cache.manifest_path(&job.identity)?)
        .ok()
        .filter(|manifest| manifest_is_for_photo_target(manifest, &job.identity));
    let process_result = {
        let _permit = inner.native_work.acquire();
        (inner.process)(&job.jpeg, job.container_orientation, job.identity.target)
    };
    let processed = match process_result {
        Ok(processed) => match validate_processed(&processed, job.identity.target) {
            Ok(()) => processed,
            Err(error) => return persist_or_stale(inner, job, prior, error),
        },
        Err(error) => return persist_or_stale(inner, job, prior, error),
    };

    // Holding the state lock makes cache shutdown and invalidation the publication
    // linearization points: either one winning first suppresses all old output.
    let state = inner.state.lock().expect("scheduler state poisoned");
    if state.closed {
        drop(state);
        return Err(CacheError::Closed);
    }
    if !state.generation_is_authoritative(&job.manifest_key, job.generation) {
        drop(state);
        return Err(CacheError::Invalidated);
    }
    let published = match publish_derivative(&inner.cache, &final_path, &processed) {
        Ok(()) => true,
        Err(_) => {
            drop(state);
            return persist_or_stale(inner, job, prior, DerivativeError::Internal);
        }
    };
    let current = manifest_record(
        &job.identity,
        &job.key,
        processed.width,
        processed.height,
        processed.profile,
    );
    let manifest_published = state.generation_is_authoritative(&job.manifest_key, job.generation)
        && publish_manifest(&inner.cache, &job.identity, &current).is_ok();
    drop(state);
    if published && manifest_published {
        Ok(DerivativeResult::Ready(cached_from_manifest(
            &inner.cache,
            current,
            ManifestFacts {
                width: processed.width,
                height: processed.height,
            },
            true,
            false,
        )))
    } else if published {
        // Bytes without an authoritative manifest are never reported current.
        // Only a manifest that was already durable before this attempt can be
        // returned as stale; the just-built bytes have no trusted identity.
        persist_or_stale(inner, job, prior, DerivativeError::Internal)
    } else {
        Err(CacheError::Io)
    }
}

fn persist_or_stale(
    inner: &SchedulerInner,
    job: &QueuedJob,
    prior: Option<Manifest>,
    error: DerivativeError,
) -> Result<DerivativeResult, CacheError> {
    let classified = failure_for_error(error);
    let mut state = inner.state.lock().expect("scheduler state poisoned");
    if !state.generation_is_authoritative(&job.manifest_key, job.generation) {
        return Err(CacheError::Invalidated);
    }
    if matches!(
        classified.kind,
        DerivativeFailureKind::Unsupported
            | DerivativeFailureKind::Malformed
            | DerivativeFailureKind::ResourceLimit
    ) {
        let _ = persist_failure(
            &inner.cache.failure_path(&job.key),
            failure_record(&job.identity, &job.key, classified.kind),
        );
        state.failed.insert(job.key.clone(), classified.clone());
    }
    drop(state);
    let result = if let Some(manifest) = prior
        && let Some(stale) = stale_derivative(&inner.cache, manifest, job.identity.target)
    {
        Ok(DerivativeResult::Ready(stale))
    } else {
        Ok(DerivativeResult::Failed(DerivativeFailure {
            kind: classified.kind,
        }))
    };
    authoritative_result(inner, job, result)
}

fn stale_or_failure(
    inner: &SchedulerInner,
    identity: &DerivativeIdentity,
    failure: FailureRecord,
) -> Result<DerivativeResult, CacheError> {
    if let Ok(manifest) = read_manifest(&inner.cache.manifest_path(identity)?)
        && manifest_is_stale_for_identity(&manifest, identity)
        && let Some(stale) = stale_derivative(&inner.cache, manifest, identity.target)
    {
        return Ok(DerivativeResult::Ready(stale));
    }
    Ok(DerivativeResult::Failed(DerivativeFailure {
        kind: failure.kind.into(),
    }))
}

/// A prior manifest whose persisted bytes still validate serves as the stale
/// fallback for a failed or superseded generation attempt.
fn stale_derivative(
    cache: &CacheDirectory,
    manifest: Manifest,
    target: DerivativeTarget,
) -> Option<CachedDerivative> {
    let facts = inspect_cached(&cache.derivative_path(&manifest.key), target, &manifest)?;
    Some(cached_from_manifest(cache, manifest, facts, false, true))
}

fn publish_derivative(
    cache: &CacheDirectory,
    final_path: &Path,
    processed: &Derivative,
) -> Result<(), CacheError> {
    let temporary = cache.root().join(format!(
        ".{}.{}.{}.tmp",
        final_path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or(CacheError::UnsupportedEncoding)?,
        std::process::id(),
        NEXT_TEMPORARY.fetch_add(1, Ordering::Relaxed)
    ));
    publish_atomic(&temporary, final_path, &processed.jpeg)
}

fn publish_atomic(temporary: &Path, path: &Path, bytes: &[u8]) -> Result<(), CacheError> {
    write_new_file(temporary, bytes)?;
    match fs::rename(temporary, path) {
        Ok(()) => Ok(()),
        Err(_) => {
            let _ = fs::remove_file(temporary);
            Err(CacheError::Io)
        }
    }
}

// JSON publications intentionally derive a sibling temporary with `with_extension`;
// changing that naming would alter cleanup and crash-recovery behavior.
fn publish_json(path: &Path, bytes: &[u8]) -> Result<(), CacheError> {
    let temporary = path.with_extension(format!(
        "json.{}.{}.tmp",
        std::process::id(),
        NEXT_TEMPORARY.fetch_add(1, Ordering::Relaxed)
    ));
    publish_atomic(&temporary, path, bytes)
}

fn publish_manifest(
    cache: &CacheDirectory,
    identity: &DerivativeIdentity,
    manifest: &Manifest,
) -> Result<(), CacheError> {
    let path = cache.manifest_path(identity)?;
    let bytes = serialize_manifest(manifest)?;
    publish_json(&path, &bytes)
}

fn write_new_file(path: &Path, bytes: &[u8]) -> Result<(), CacheError> {
    let result = (|| {
        let mut file = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(path)
            .map_err(|_| CacheError::Io)?;
        file.write_all(bytes).map_err(|_| CacheError::Io)?;
        file.sync_all().map_err(|_| CacheError::Io)?;
        Ok::<(), CacheError>(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(path);
    }
    result
}

fn persist_failure(path: &Path, failure: FailureRecord) -> Result<(), CacheError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|_| CacheError::Io)?;
    }
    let bytes = serialize_failure(&failure)?;
    publish_json(path, &bytes)
}

fn remove_if_present(path: &Path) -> Result<(), CacheError> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(_) => Err(CacheError::Io),
    }
}

fn failure_for_error(error: DerivativeError) -> DerivativeFailure {
    DerivativeFailure {
        kind: match error {
            DerivativeError::Unsupported => DerivativeFailureKind::Unsupported,
            DerivativeError::Malformed => DerivativeFailureKind::Malformed,
            DerivativeError::ResourceLimit => DerivativeFailureKind::ResourceLimit,
            DerivativeError::OutputLimit => DerivativeFailureKind::ResourceLimit,
            DerivativeError::Internal => DerivativeFailureKind::Internal,
        },
    }
}

fn selected_original<'a>(
    photo: &PhotoRecord,
    originals: &'a [OriginalRecord],
) -> Option<(PreviewSource, &'a OriginalRecord)> {
    originals.iter().find_map(|original| {
        (original.id == photo.original_id
            && original.available
            && original.error_category.is_none())
        .then_some((original.kind.preview_source(), original))
    })
}

fn inspect_cached(
    path: &Path,
    target: DerivativeTarget,
    manifest: &Manifest,
) -> Option<ManifestFacts> {
    let metadata = fs::symlink_metadata(path).ok()?;
    if !metadata.is_file() || metadata.len() == 0 || metadata.len() > MAXIMUM_OUTPUT_BYTES {
        return None;
    }
    let file = OpenOptions::new()
        .read(true)
        .custom_flags(no_follow_flag())
        .open(path)
        .ok()?;
    let mut bytes = Vec::with_capacity(metadata.len() as usize);
    file.take(MAXIMUM_OUTPUT_BYTES + 1)
        .read_to_end(&mut bytes)
        .ok()?;
    if bytes.len() as u64 > MAXIMUM_OUTPUT_BYTES {
        return None;
    }
    let facts = jpeg_facts(&bytes)?;
    if facts.width != manifest.width
        || facts.height != manifest.height
        || facts.width.max(facts.height) > target.long_edge()
    {
        return None;
    }
    validate_cached_jpeg(&bytes, facts, manifest.color_profile)?;
    Some(facts)
}

fn cached_from_manifest(
    cache: &CacheDirectory,
    manifest: Manifest,
    facts: ManifestFacts,
    generated: bool,
    stale: bool,
) -> CachedDerivative {
    let cache_path = cache.derivative_path(&manifest.key);
    CachedDerivative {
        cache_path,
        cache_key: manifest.key,
        source: manifest.source,
        source_relative_path: manifest.source_relative_path,
        source_size: manifest.source_size,
        source_mtime_ms: manifest.source_mtime_ms,
        embedded_candidate_identity: manifest.embedded_candidate_identity,
        width: facts.width,
        height: facts.height,
        profile: manifest.color_profile.into(),
        generated,
        stale,
    }
}

pub fn derivative_cache_key(identity: &DerivativeIdentity) -> Result<String, CacheError> {
    identity.validate()?;
    #[derive(Serialize)]
    struct Key<'a> {
        version: &'static str,
        photo: &'a str,
        source: DerivativeSource,
        path: &'a str,
        size: u64,
        #[serde(rename = "mtimeMs")]
        mtime_ms: f64,
        candidate: Option<&'a str>,
        edge: u32,
    }
    let key = Key {
        version: DERIVATIVE_ALGORITHM_VERSION,
        photo: &identity.photo_identity,
        source: identity.source,
        path: &identity.source_relative_path,
        size: identity.source_size,
        mtime_ms: identity.source_mtime_ms,
        candidate: identity.embedded_candidate_identity.as_deref(),
        edge: identity.target.long_edge(),
    };
    Ok(hex_digest(
        &serde_json::to_vec(&key).map_err(|_| CacheError::InvalidIdentity)?,
    ))
}

fn manifest_identity_for_photo_target(
    photo_id: &str,
    target: DerivativeTarget,
) -> Result<String, CacheError> {
    if photo_id.is_empty() || photo_id.contains('\0') {
        return Err(CacheError::InvalidIdentity);
    }
    #[derive(Serialize)]
    struct Key<'a> {
        photo: &'a str,
        edge: u32,
    }
    let key = Key {
        photo: photo_id,
        edge: target.long_edge(),
    };
    Ok(hex_digest(
        &serde_json::to_vec(&key).map_err(|_| CacheError::InvalidIdentity)?,
    ))
}

pub fn manifest_identity(identity: &DerivativeIdentity) -> Result<String, CacheError> {
    identity.validate()?;
    manifest_identity_for_photo_target(&identity.photo_identity, identity.target)
}

fn hex_digest(bytes: &[u8]) -> String {
    let mut digest = Sha256::new();
    digest.update(bytes);
    format!("{:x}", digest.finalize())
}

fn is_hex_key(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
}

fn reject_cache_under_original(
    cache_directory: &Path,
    canonical_original_root: &Path,
) -> Result<(), CacheError> {
    let lexical_cache = lexical_absolute_path(cache_directory)?;
    if lexical_cache == canonical_original_root
        || lexical_cache.starts_with(canonical_original_root)
    {
        return Err(CacheError::InvalidCacheDirectory);
    }
    let mut existing = cache_directory;
    while !existing.exists() {
        existing = existing.parent().ok_or(CacheError::InvalidCacheDirectory)?;
    }
    let canonical_existing =
        fs::canonicalize(existing).map_err(|_| CacheError::InvalidCacheDirectory)?;
    if canonical_existing == canonical_original_root
        || canonical_existing.starts_with(canonical_original_root)
    {
        return Err(CacheError::InvalidCacheDirectory);
    }
    Ok(())
}

fn lexical_absolute_path(path: &Path) -> Result<PathBuf, CacheError> {
    let mut result = PathBuf::new();
    for component in path.components() {
        match component {
            Component::RootDir => result.push(component.as_os_str()),
            Component::Normal(value) => result.push(value),
            Component::CurDir => {}
            Component::ParentDir => {
                result.pop();
            }
            Component::Prefix(_) => return Err(CacheError::InvalidCacheDirectory),
        }
    }
    Ok(result)
}

fn is_safe_relative_utf8_path(value: &str) -> bool {
    let path = Path::new(value);
    if value.is_empty() || path.is_absolute() {
        return false;
    }
    path.components()
        .all(|component| matches!(component, Component::Normal(_)))
}

#[cfg(unix)]
const fn no_follow_flag() -> i32 {
    libc::O_NOFOLLOW | libc::O_CLOEXEC
}

#[cfg(not(unix))]
const fn no_follow_flag() -> i32 {
    0
}

#[cfg(test)]
#[path = "cache_tests.rs"]
mod tests;