[package]
name = "slipstream-cli"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "slipstream"
path = "src/main.rs"

[dependencies]
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["time"] }
url.workspace = true

[dev-dependencies]
slipstream-server = { path = "../slipstream-server" }
